title: NEO Workshop 2025
description: NEO Workshop program
baseurl: "https://NEO-Research-Group.github.io/neo-workshops"
url: "https://NEO-Research-Group.github.io/neo-workshops"

theme: jekyll-theme-architect

author:
  name: Francisco Chicano
  email: chicano@uma.es
