title: NEO Workshop 2025
description: NEO Workshop program
baseurl: "https://NEO-Research-Group.github.io/neo-workshops"
url: "https://NEO-Research-Group.github.io/neo-workshops"

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

author:
  name: Francisco Chicano
  email: chicano@uma.es
