# _config.yml

title: NEO Workshop 2025
description: NEO Workshop program
baseurl: ""  # no pongas nada aquí si el repositorio es username.github.io
url: "https://NEO-Research-Group.github.io/neo-workshops"  # reemplaza con tu nombre de usuario de GitHub

# Tema de Jekyll (soportado por GitHub Pages)
theme: jekyll-theme-minimal

# Datos del autor (opcional)
author:
  name: Francisco Chicano
  email: chicano@uma.es

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Excluye carpetas innecesarias del build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
